/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pjk.dayschedule;

import java.text.DateFormatSymbols;
import java.time.DayOfWeek;
import java.time.LocalDate;

/**
 *
 * @author pkacperski
 */
public class DatePanel extends javax.swing.JPanel {

  private final String[] shortDayNames;

  /**
   * Creates new form DatePanel
   */
  public DatePanel() {
    initComponents();
    shortDayNames = new DateFormatSymbols().getShortWeekdays();

    var now = LocalDate.now();
    dayOfMonthLabel.setText("" + now.getDayOfMonth());
    dayOfWeekLabel.setText(getShortDayName(now.getDayOfWeek()));
  }

  private String getShortDayName(DayOfWeek day) {
    var i = day.getValue() + 1;
    if (i >= 1 && i < shortDayNames.length) {
      return shortDayNames[i];
    }
    return day.toString();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayOfMonthLabel = new javax.swing.JLabel();
        dayOfWeekLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        dayOfMonthLabel.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        dayOfMonthLabel.setForeground(new java.awt.Color(50, 50, 50));
        dayOfMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfMonthLabel.setText("24");
        dayOfMonthLabel.setFocusable(false);
        dayOfMonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dayOfWeekLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dayOfWeekLabel.setForeground(new java.awt.Color(50, 50, 50));
        dayOfWeekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfWeekLabel.setText("Mon");
        dayOfWeekLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dayOfMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(dayOfWeekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dayOfMonthLabel)
                .addGap(0, 0, 0)
                .addComponent(dayOfWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayOfMonthLabel;
    private javax.swing.JLabel dayOfWeekLabel;
    // End of variables declaration//GEN-END:variables
}
