/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pjk.dayschedule;

import java.time.format.DateTimeFormatter;

/**
 *
 * @author pkacperski
 */
public class EditScheduleItemForm extends javax.swing.JDialog {

  public enum DialogResult {
    None,
    Save,
    Cancel
  }

  private DialogResult dialogResult = DialogResult.None;
  private ScheduleItem item;

  /**
   * Creates new form NewJDialog
   */
  public EditScheduleItemForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    getContentPane().setBackground(getBackground());
    getRootPane().setDefaultButton(saveButton);
  }

  public void setItem(ScheduleItem item) {
    this.item = item;
    deserializeItem();
  }

  private void serializeItem() {
    item.setCaption(captionTextField.getText());
  }

  private void deserializeItem() {
    startTimeLabel.setText(item.getStartTime().format(DateTimeFormatter.ofPattern("h:mm a")));
    stopTimeLabel.setText(item.getStopTime().format(DateTimeFormatter.ofPattern("h:mm a")));
    captionTextField.setText(item.getCaption());
  }

  public DialogResult getDialogResult() {
    return dialogResult;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        labelStopTimeLabel = new javax.swing.JLabel();
        labelStartTimeLabel = new javax.swing.JLabel();
        captionTextField = new javax.swing.JTextField();
        stopTimeLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        labelCaptionLabel = new javax.swing.JLabel();

        setTitle("Edit Schedule Item");
        setBackground(new java.awt.Color(255, 255, 255));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        labelStopTimeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelStopTimeLabel.setText("Stop time");

        labelStartTimeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelStartTimeLabel.setText("Start time");

        captionTextField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        captionTextField.setText("New Schedule Item");

        stopTimeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        stopTimeLabel.setText("9:00 PM");

        startTimeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        startTimeLabel.setText("8:00 PM");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        labelCaptionLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelCaptionLabel.setText("Caption");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCaptionLabel)
                            .addComponent(labelStartTimeLabel)
                            .addComponent(labelStopTimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(captionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(stopTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaptionLabel)
                    .addComponent(captionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(labelStartTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopTimeLabel)
                    .addComponent(labelStopTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    serializeItem();
    dialogResult = DialogResult.Save;
    setVisible(false);
  }//GEN-LAST:event_saveButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dialogResult = DialogResult.Cancel;
    setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField captionTextField;
    private javax.swing.JLabel labelCaptionLabel;
    private javax.swing.JLabel labelStartTimeLabel;
    private javax.swing.JLabel labelStopTimeLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JLabel stopTimeLabel;
    // End of variables declaration//GEN-END:variables
}
